import os
from pathlib import Path
from datetime import timedelta

def create_settings(config_name="config", selected_features=None):
    """Refactored to ONLY handle setting up the split settings architecture."""
    
    if selected_features is None:
        selected_features = []

    # 1. Target the config folder generated by startproject
    base_dir = Path.cwd()
    config_dir = base_dir / config_name
    settings_dir = config_dir / "settings"

    # Remove the default monolithic settings.py created by Django
    default_settings_file = config_dir / "settings.py"
    if default_settings_file.exists():
        default_settings_file.unlink()

    os.makedirs(settings_dir, exist_ok=True)

    # ==========================================
    # DYNAMIC INJECTIONS
    # ==========================================
    additional_apps = []
    if "celery" in selected_features:
        additional_apps.append('\n    "django_celery_results",')
    if "beat" in selected_features:
        additional_apps.append('\n    "django_celery_beat",')

    whitenoise_middleware = ""
    whitenoise_settings = ""
    if "whitenoise" in selected_features:
        whitenoise_middleware = '\n    "whitenoise.middleware.WhiteNoiseMiddleware",'
        whitenoise_settings = '\n# WhiteNoise Static Files Storage\nSTATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"\n'

    # ==========================================
    # FILE TEMPLATES
    # ==========================================
    base_settings = f"""from pathlib import Path
import os
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent.parent
SECRET_KEY = os.getenv("SECRET_KEY", "fallback-insecure-key-for-dev")
DEBUG = False
ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # ==========================
    # Third-party apps
    # ==========================
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt",{"".join(additional_apps)}

    # ==========================
    # Local apps
    # ==========================
    # "accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",{whitenoise_middleware}
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "{config_name}.urls"

TEMPLATES = [
    {{
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {{
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        }},
    }},
]

WSGI_APPLICATION = "{config_name}.wsgi.application"

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"{whitenoise_settings}
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==========================================
# CORS & CSRF Configuration
# ==========================================
env_cors = os.getenv("CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in env_cors.split(",") if origin.strip()]

env_csrf = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in env_csrf.split(",") if origin.strip()]

# ==========================================
# REST Framework & JWT Configuration
# ==========================================
REST_FRAMEWORK = {{
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ]
}}

SIMPLE_JWT = {{
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
}}

# ==========================================
# Celery Configuration
# ==========================================
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
"""

    dev_settings = """from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / ".env.development")

from .base import *

DEBUG = True
ALLOWED_HOSTS = ["*"]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
"""

    prod_settings = """import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / ".env.production")

from .base import *

DEBUG = False
env_hosts = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [host.strip() for host in env_hosts.split(",") if host.strip()]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}
"""

    # ==========================================
    # FILE WRITER HELPER
    # ==========================================
    def write_file(path, content):
        with open(path, "w") as f:
            f.write(content)

    # ==========================================
    # EXECUTE GENERATION
    # ==========================================
    write_file(settings_dir / "__init__.py", "from .development import *\n")
    write_file(settings_dir / "base.py", base_settings)
    write_file(settings_dir / "development.py", dev_settings)
    write_file(settings_dir / "production.py", prod_settings)